//t图片+miaoshu，w文字,
//---------------通知旧to新---------------------------

//---------------通知1---------------------------
document.getElementById("w1").innerHTML="欢迎来到橙子网!";
document.getElementById("w1").href="#"; 
//---------------通知2---------------------------
document.getElementById("t2").alt="橙子电影院欢迎您!";
document.getElementById("t2").src="image/cinema.png";
document.getElementById("w2").innerHTML="橙子电影院来啦!点我进入!";
document.getElementById("w2").href="../ordylan_cinema/index.html"; 
//---------------通知3---------------------------
document.getElementById("w3").innerHTML="主页大改版，快来看看吧~";
document.getElementById("w3").href="../../mainpage/index.html"; 
//---------------通知4---------------------------
document.getElementById("t4").alt="橙鸭快乐跳2来啦";
document.getElementById("t4").src="image/20200825.svg";
document.getElementById("w4").innerHTML="橙鸭快乐跳2来啦，点我去玩&gt;&gt;";
document.getElementById("w4").href="../ordylan_game/games/o_jump_2/index.html"; 
//---------------通知5---------------------------
document.getElementById("t5").alt="橙子网一周年啦!";
document.getElementById("t5").src="../../mainpage/image/logo1year.svg";
document.getElementById("w5").innerHTML="橙子网一周年啦!";
document.getElementById("w5").href="../ordylan_article/articles/2020.9.25_1/index.html"; 
//---------------通知6---------------------------
document.getElementById("t6").alt="橙子网4.0庆典已经到来";
document.getElementById("t6").src="../../mainpage/huodong/qingdian/youwanquan.png";
document.getElementById("w6").innerHTML="橙子网4.0庆典已经到来,快来庆典游玩吧!";
document.getElementById("w6").href="../ordylan_article/articles/2020.10.18_1/index.html"; 
//---------------通知7---------------------------
document.getElementById("w7").innerHTML="每页一句来啦,每次加载文字都会变哦~";